python/app/blueprints/home_bp.py
from flask import Blueprint, render_template

from flask_security import Security, SQLAlchemyUserDatastore, auth_required

from flask_security.models import fsqla_v3 as fsqla

from flask_login import current_user

import random

home_bp = Blueprint('home_bp', __name__)

@home_bp.route('/app/', methods=['GET', 'POST'])
def rootofserver():
    return 'the name is root'

@home_bp.route('/app/home')
def home():
    return render_template('home.html')

# Views
@home_bp.route("/app/heart")
def heart():
    return render_template_string('Home is where the heart is !')

@home_bp.route("/app/hello")
@auth_required()
def hello():
    return render_template_string('Hello {{email}} !', email=current_user.email)

@home_bp.route('/app/welcome/')
@auth_required()
def welcome():
    return render_template('welcome.html')


@home_bp.route('/app/dash/')
def homepage():
    return """
    <h1>Hello world!</h1>

    <iframe src="../wsgi_app2" width="853" height="480" frameborder="0" allowfullscreen></iframe>
    """



'''
@home_bp.route('/app/dash/')
def dashit():
    urls = [
        'http://www.w3schools.com',
        'http://techcrunch.com/',
        'https://www.fayerwayer.com/',
    ]

    iframe = random.choice(urls)

    return render_template('iframe.html', iframe=iframe)
'''

python/app/templates/base.html
<!doctype html>
<html>
  <head>
    <title>{{title}}</title>
    <meta charset="utf-8">
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

python/app/templates/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{{ title }}</title>
</head>
<body>
     <p> i am in base</p>
     <div>
        <a href="{{ url_for('index') }}">Home</a>
        {% if current_user.is_anonymous %}
        <a href="{{ url_for('security.login') }}">Login</a>
        {% else %}
        <a href="{{ url_for('security.logout') }}">Logout</a>
        {% endif %}
    </div>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <ul class="flash">
            {% for category, message in messages %}
              <li class="{{ category }}">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    {% endwith %}
    
    {% if current_user.is_authenticated %}
      You are logged in as {{ current_user.username }}!
      <a href="{{ url_for('security.logout') }}">Log out</a>
    {% else %}
      You are not logged in.
      <a href="{{ url_for('security.login') }}">Login</a>
    {% endif %}
    
{% block main %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

python/app/templates/base_old.html
<html>
    <head>
        {% if title %}
        <title>{{ title }} - microblog</title>
        {% else %}
        <title>microblog</title>
        {% endif %}
    </head>
    <body>
        <div>
            <a href="{{ url_for('index') }}">Home</a>
            {% if current_user.is_anonymous %}
            <a href="{{ url_for('gitlogin') }}">Login</a>
            {% else %}
            <a href="{{ url_for('logout') }}">Logout</a>
            {% endif %}
        </div>
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            <ul class="flash">
            {% for category, message in messages %}
              <li class="{{ category }}">{{ message }}</li>
            {% endfor %}
            </ul>
          {% endif %}
        {% endwith %}
        {% if current_user.is_authenticated %}
          You are logged in as {{ current_user.username }}!
          <a href="{{ url_for("logout") }}">Log out</a>
        {% else %}
          You are not logged in.
          <a href="{{ url_for("github.login") }}">Log in</a>
        {% endif %}
        {% block content %}{% endblock %}
    </body>
</html>

python/app/templates/create_plot.html
{% block content %}

<div class="container">
	<div class="row pb-5">
		<div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto">

		<h1 class="pt-5 pb-2">Create New Plot</h1>

		{% if message %}

			<!-- the form was submitted and message exists -->
			<p class="lead"><strong>{{ message }}</strong></p>

			<!-- links -->
			<p><a href="{{ url_for('plotids_bp.FuncCreatePlot') }}">Create another Plot</a></p>

			<p><a href="{{ url_for('home_bp.home') }}">Return to the index.</a></p>

		{% else %}

			<!-- the form is displayed when template opens via GET not POST -->
			<p class="lead alert alert-primary">Create a new plot.</p>
			<p class="ml-4"><a href="{{ url_for('home_bp.home') }}">Return to the home.</a></p>

			{% with errors = get_flashed_messages() %}
				{% if errors %}
					{% for err in errors %}
						<div class="alert alert-danger alert-dismissible" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">×</span></button>
						{{ err }}
						</div>
					{% endfor %}
				{% endif %}
			{% endwith %}
			<!-- end of flash -->

			 <div class="form-wrapper">
			      <h2 class="title">New Plot</h2>

			      <form method="POST" action="{{ url_for('plotids_bp.FuncCreatePlot') }}">
			      {{ form1.csrf_token }}
				      
			      <fieldset class="form-field">
				  {{ form1.name.label }}
				  {{ form1.name }}
			      </fieldset>

			      <fieldset class="form-field">
				  {{ form1.plotid.label }}
				  {{ form1.plotid }}
			      </fieldset>

			      {{ form1.submit }}

			      </form>
    			</div>

		{% endif %}

		</div>
	</div>
</div>

{% endblock %}

python/app/templates/dash1.html
{% extends "base.html" %}
{% block main %}
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class="flash">
    {% for category, message in messages %}
      <li class="{{ category }}">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
{% if current_user.is_authenticated %}
  You are logged in as {{ current_user.username }}!
  <a href="{{ url_for("security.logout") }}">Log out</a>
{% else %}
  You are not logged in.
  <a href="{{ url_for("security.login") }}">Log in</a>
{% endif %}
<iframe src="https://www.w3schools.com" title="W3Schools Free Online Web Tutorials"></iframe> 
{% endblock %}

python/app/templates/iframe.html
{% extends 'layout.html' %}
{% block content %}
   <iframe frameborder='0' noresize='noresize'
           style='position: absolute; background: transparent; width: 100%; height:100%;'
           src="{{ iframe }}"
           frameborder="0"></iframe>
{% endblock content %}

python/app/templates/index.html
{% extends "base.html" %}
{% block main %}
    <h1>Hi, {{ user.username }}!!!!</h1>
{% endblock %}

python/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    {% block content %} 
    {% endblock content %}

</body>
</html>

python/app/templates/listplots.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="title">{% block title %} All Plots {% endblock %}</h1>
    <div class="content">
        {% for plot in plots_in %}
            <div class="plots">
                <p><b>#{{ plot.id }}</b></p>
                <b>
                    <p class="name">{{ plot.plotid }}</p>
                </b>
                <p>{{ plotid.name }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

python/app/templates/old_register.html
{% extends "base.html" %}

{% block main %}
    <h1>Register</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

python/app/templates/read_plot.html
{% block content %}

<div class="container">
	<div class="row pb-5">
		<div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto">

		<h1 class="pt-5 pb-2">Create New Plot</h1>

		{% if message %}

			<!-- the form was submitted and message exists -->
			<p class="lead"><strong>{{ message }}</strong></p>

			<!-- links -->
			<p><a href="{{ url_for('plotids_bp.FuncCreatePlot') }}">Create another Plot</a></p>

			<p><a href="{{ url_for('home_bp.home') }}">Return to the index.</a></p>

		{% else %}

			<!-- the form is displayed when template opens via GET not POST -->
			<p class="lead alert alert-primary">Create a new plot.</p>
			<p class="ml-4"><a href="{{ url_for('home_bp.home') }}">Return to the home.</a></p>

			{% with errors = get_flashed_messages() %}
				{% if errors %}
					{% for err in errors %}
						<div class="alert alert-danger alert-dismissible" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">×</span></button>
						{{ err }}
						</div>
					{% endfor %}
				{% endif %}
			{% endwith %}
			<!-- end of flash -->

			 <div class="form-wrapper">
			      <h2 class="title">New Plot</h2>

			      <form method="POST" action="{{ url_for('plotids_bp.FuncCreatePlot') }}">
			      {{ form1.csrf_token }}
				      
			      <fieldset class="form-field">
				  {{ form1.name.label }}
				  {{ form1.name }}
			      </fieldset>

			      <fieldset class="form-field">
				  {{ form1.plotid.label }}
				  {{ form1.plotid }}
			      </fieldset>

			      {{ form1.submit }}

			      </form>
    			</div>

		{% endif %}

		</div>
	</div>
</div>

{% endblock %}

python/app/templates/test.html
{% extends 'base.html' %}

{% block main %}
<h1>Make A Short URL</h1>
{% for message in get_flashed_messages() %}
<h2>{{ message }}</h2>
{% endfor %}
<form action="shortenurl" method="post">
    <label for="url">Enter URL</label>
    <input type="url" name="url" value="" required>
    <label for="shortcode">Enter Name</label>
    <input type="text" name="shortcode" value="" required>
    <input type="submit" value="Submit">
</form>
{% endblock %}

python/app/templates/user.html
<!doctype html>
<html>
    <head>
        <title>{{ title }}</title>
    </head>
    <body>
        <h1>Hello, {{ user.username }}!</h1>
    </body>
</html>

python/app/templates/welcome.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Welome to DM Tools Site!</title>
  </head>
  <body>
    <h1>This is a welcome page with Bootstrap Support!</h1>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
  </body>
</html>